# Generated by Django 4.2.23 on 2025-10-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_github_user_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_given',
            field=models.BooleanField(default=False),
        ),
    ]
